### ISSUE TITLE
点击或者拖动的时候监听事件失效

### ISSUE THREAD

**Issue by AndMy** [giswangsj/AndRatingBar#10]
ratingBar.setOnRatingChangeListener { ratingBar, rating ->
   Log.e("ratingBar", "rating:$rating")
}
首次进入界面有打印，然后点击或者拖动的时候没有打印

**Comment by giswangsj** [comment]
你是不是看的demo中的SizeFragment中的事件，代码中ratingBar1是36dp的那个，而不是16dp的那个，你再试一下看。代码已更新，在界面上可以直接看到rating变化值。

**Comment by AndMy** [comment]
嗯嗯，我知道了，是我这里的原因，kontlin include布局中的ratingbar，然后我再activity里直接用了，没有用findviewbyid来引入；但是第一次竟然打印了，当时就没注意，非常感谢大佬的回复，谢谢谢谢诶

**Comment by giswangsj** [comment]
好的，没问题就好
