### ISSUE TITLE
请教一下作者，这里面有设置星星之间的间隔的属性吗？

### ISSUE THREAD

**Issue by hardgit** [giswangsj/AndRatingBar#7]
请教一下作者，这里面有设置星星之间的间隔的属性吗？

**Comment by giswangsj** [comment]
有两种方式：1，可以通过setScaleFactor()按比例对ratingbar进行缩放，可以调整间距。2，通过setStarSpacing()来对ratingbar默认的间距进行调整，增加减少都可以。可以参看最新的代码及文档。PS：如果你设置了ratingbar的宽度，则间距自动适应控件宽度

**Comment by giswangsj** [comment]
推荐这个试一下
