### ISSUE TITLE
android6.0以下版本机器运行崩溃

### ISSUE THREAD

**Issue by segerbing** [giswangsj/AndRatingBar#8]
主要是在6.0以下的版本中  ClipDrawable  没有  getDrawable()  这个方法，我的解决方式是在 
   StartDrawable   这个类的    getTileDrawableByLayerId(int id)    这个方法中加入了版本判断，6.0以下版本使用反射获取  drawable，并且把    @SuppressLint("NewApi")     这个注解去掉，具体代码如下`

            case android.R.id.secondaryProgress:
            case android.R.id.progress: {
                ClipDrawable clipDrawable = (ClipDrawable) layerDrawable;
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
                    return (TileDrawable) clipDrawable.getDrawable();
                }else {
                    try {
                        Field mStateField = clipDrawable.getClass().getDeclaredField("mState");
                        mStateField.setAccessible(true);
                        Object clipState = mStateField.get(clipDrawable);
                        Field mDrawableField = clipState.getClass().getDeclaredField("mDrawable");
                        mDrawableField.setAccessible(true);
                        return (TileDrawable) mDrawableField.get(clipState);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }`

**Comment by giswangsj** [comment]
谢谢大佬的指正，已经修复此bug

**Comment by 401885064** [comment]
坑。。。Android5.0以下不叫mState了，叫mClipState。。。。  所以还要加判断

**Comment by giswangsj** [comment]
这个问题已经解决了，最新的代码改过了，忘记发布版本了，用1.0.5版本就好了
